name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build release
        run: cargo build --release --locked
      - name: Package release
        run: tar -zcf friggen-linux-x86_64.tar.gz -C target/release friggen
      - name: Publish release
        uses: softprops/action-gh-release@v2.0.4
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          draft: false
          files: friggen-linux-x86_64.tar.gz
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
