name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  release:
    name: ${{ matrix.platform.os_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: friggen
            archive_suffix: linux-x86_64.tar.gz
          - os_name: Linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            bin: friggen
            archive_suffix: linux-aarch64.tar.gz
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: friggen
            archive_suffix: darwin-x86_64.tar.gz
          - os_name: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: friggen
            archive_suffix: darwin-aarch64.tar.gz

    steps:
      - uses: actions/checkout@v4

      - name: Cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Get release version
        shell: bash
        run: |
          tag="${{github.ref_name}}"
          tag_version="${tag#v}"
          cargo_version=$(grep 'version' Cargo.toml | head -1 | cut -d' ' -f3 | tr -d '"')
          if [[ $tag_version != $cargo_version ]]; then
            echo "tag and cargo version do not match: tag version = $tag_version, cargo version = $cargo_version" >&2
            exit 1
          fi
          echo "friggen_version=$tag_version" >> $GITHUB_ENV

      - name: Test
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: test
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"

      - name: Build release
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true

      - name: Package release
        shell: bash
        run: |
          archive="friggen-${{ env.friggen_version }}-${{ matrix.platform.archive_suffix }}"
          tar -zcf "$archive" -C target/${{ matrix.platform.target }}/release ${{ matrix.platform.bin }}

      - name: Publish release
        uses: softprops/action-gh-release@v2.0.4
        with:
          draft: true
          files: friggen-*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
